room/urls.py
from django.conf.urls import url

from . import views

app_name = 'room'
urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^about/$', views.about, name='about'),
	url(r'^create-case/$', views.create_case, name='create_case'),
	url(r'^create-room/$', views.create_room, name='create_room'),
	url(r'^create-group/$', views.create_group, name='create_group'),
	url(r'^case/(?P<pk>.*)/$', views.CaseView.as_view(), name='case'),
]

roomalloc/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

urlpatterns = [
    url(r'^room/', include('room.urls')),
    url(r'^admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

room/models.py
from __future__ import unicode_literals

import datetime
import os.path as osp
import pickle
from django.db import models
from django.conf import settings
from algo import Simplex


class Case(models.Model):
	name = models.CharField(max_length=200, primary_key=True)
	created_date = models.DateTimeField(default=datetime.datetime.now, blank=True)
	img = models.ImageField(default=None)
	rent = models.IntegerField(default=0)

	def __unicode__(self):
		return self.name

	def get_num_groups(self):
		return Group.objects.filter(case=self).count()

class Room(models.Model):
	case = models.ForeignKey(Case, on_delete=models.CASCADE)
	name = models.CharField(max_length=200)
	price = models.IntegerField(default=0)

	def __unicode__(self):
		return self.name


class Group(models.Model):
	case = models.ForeignKey(Case, on_delete=models.CASCADE)
	name = models.CharField(max_length=200)
	num_of_renters = models.IntegerField(default=1)
	is_online = models.BooleanField(default=False)
	is_ready = models.BooleanField(default=False)

	accept = models.BooleanField(default=False)
	voted = models.BooleanField(default=False)

	def __unicode__(self):
		return self.name

	def login(self):
		self.is_online = True
		self.save()

	def ready(self):
		self.is_ready = True
		self.save()

	def logout(self):
		self.is_online = False
		self.is_ready = False
		self.save()

	def vote(self, choice):
		self.accept = choice
		self.voted = True
		self.save()



class Allocation(models.Model):
	case = models.OneToOneField(Case, on_delete=models.CASCADE, primary_key=True)

	def __init__(self, case_name, *args, **kwargs):
		super(Allocation, self).__init__(*args, **kwargs)
		self.case = Case.objects.get(name=case_name)

	def __unicode__(self):
		return self.case

	def get_simplex_path(self):
		return "room/simplex/%s" % self.case

	def get_division_path(self):
		return "room/division/%s" % self.case

	def can_begin(self):
		groups = Group.objects.filter(case=self.case)
		rooms = Room.objects.filter(case=self.case)
		return rooms.count() == groups.count() and \
			groups.count() == len(filter(lambda g: g.is_online and g.is_ready, groups))

	def can_archive(self):
		if not self.is_finished_voting():
			return False
		return Group.objects.filter(case=self.case, accept=True).count() == self.case.get_num_groups()

	def is_complete(self):
		return osp.isfile(self.get_division_path())

	def is_finished_voting(self):
		# print("num_voted: %d, expected: %d" %(self.num_voted, self.case.get_num_groups()))
		return Group.objects.filter(case=self.case, voted=True).count() == self.case.get_num_groups()

	def clear_voting(self):
		for group in Group.objects.filter(case=self.case):
			group.voted = False
			voted = False
			group.save()

	def archive_division(self):
		division = self.get_suggested_division()
		division_text = pickle.dumps(division)
		with open(self.get_division_path(), "w+") as file_:
			file_.write(division_text)

	def get_archived_division(self):
		with open(self.get_division_path(), "r") as file_:
			division_text = file_.read()
		return pickle.loads(division_text)

	def get_division(self):
		if not self.is_complete:
			return None
		with open(self.get_division_path(), "r") as file_:
			division_text = file_.read()
		return pickle.loads(division_text)

	def group_number(self):
		return Group.objects.filter(case=self.case).count()

	def get_current_player(self):
		player_index = self.to_simplex().get_current_player()
		return Group.objects.filter(case=self.case).order_by("name")[player_index]

	def get_current_prices(self):
		simplex = self.to_simplex()
		prices = simplex.get_current_prices()
		return map(lambda x: self.transform_price(x), prices)

	def get_precision(self):
		splitting_rent = int(self.case.rent / 2)
		return splitting_rent * self.to_simplex().get_precision()

	def transform_price(self, raw_price):
		num_groups = self.case.get_num_groups()
		base_rent = int(self.case.rent / 2)
		effective_rent = self.case.rent - base_rent
		return int(base_rent / num_groups) + int(raw_price * effective_rent)


	def current_player_choose(self, room_index):
		'''
		Current player choose a room_index
		'''
		simplex = self.to_simplex()
		new_level = simplex.current_player_choose(room_index)
		self.update(simplex)
		return new_level

	def generate_cuts(self):
		simplex = self.to_simplex()
		player_index = simplex.get_current_player()
		player = Group.objects.filter(case=self.case).order_by("name")[player_index]
		prices = self.get_current_prices()
		return {
			'player': player,
			'prices': prices,
		}

	def get_suggested_division(self):
		division = self.to_simplex().get_suggested_division()
		# Rescale division
		for d in division:
			d['rent'] = self.transform_price(d['rent'])
		return division


	def update(self, simplex):
		'''
		Takes in a simplex object and update
		@terminate: if terminate is true, save division scheme
		'''
		simplex_text = pickle.dumps(simplex)
		with open(self.get_simplex_path(), "w+") as file_:
			file_.write(simplex_text)


	def to_simplex(self):
		'''
		Convert itself to a Simplex object 
		'''
		with open(self.get_simplex_path(), "r") as file_:
			simplex = file_.read()
		return pickle.loads(simplex)

room/forms.py
from django import forms
from django.forms import Form, ModelForm
from django.forms.widgets import Widget, HiddenInput
from django.template import Template
from django.utils.safestring import mark_safe

from .models import Case, Room, Group, Allocation

class CaseForm(ModelForm):
	class Meta:
		model = Case
		fields = ['name', 'img', 'rent', 'created_date']

class ReadOnlyCaseForm(ModelForm):
	def __init__(self, *args, **kwargs):
		super(ReadOnlyCaseForm, self).__init__(*args, **kwargs)
		instance = getattr(self, 'instance', None)
		if instance and instance.pk:
			# Disable all field
			self.fields['created_date'].widget.attrs['readonly'] = True
			self.fields['img'].widget = HiddenInput()
			self.fields['name'].widget.attrs['readonly'] = True
			self.fields['rent'].widget.attrs['readonly'] = True

	class Meta:
		model = Case
		fields = ['name', 'img', 'rent', 'created_date']

class RoomForm(ModelForm):
	def __init__(self, *args, **kwargs):
		super(RoomForm, self).__init__(*args, **kwargs)
		self.fields['case'].widget = HiddenInput()

	class Meta:
		model = Room
		fields = ['case', 'name']

class GroupForm(ModelForm):
	def __init__(self, *args, **kwargs):
		super(GroupForm, self).__init__(*args, **kwargs)
		self.fields['case'].widget = HiddenInput()

	class Meta:
		model = Group
		fields = ['case', 'name', 'num_of_renters']

class SessionForm(Form):
	group = forms.ModelChoiceField(queryset=None)

	def __init__(self, case, *args, **kwargs):
		super(SessionForm, self).__init__(*args, **kwargs)
		self.fields['group'].queryset = Group.objects.filter(case=case)

	def save(self, commit=True):
		super(SessionForm, self).save(commit=False)


		

room/views.py
from django.http import HttpResponse, HttpResponseNotFound
from django.views.generic import ListView, DetailView
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib import messages
from .models import Case, Room, Group, Allocation
from .forms import CaseForm, RoomForm, GroupForm, ReadOnlyCaseForm, SessionForm
from datetime import datetime

# Class for index view, an overview of all existing cases
class IndexView(ListView):
	template_name = 'room/index.html'
	model = Case

	def get_queryset(self):
		'''
		Return the list of all Case objects ordered by create time
		'''
		return Case.objects.order_by('-created_date')

	def get_context_data(self, **kwargs):
		'''
		Return the context of index view
		'''
		context = super(IndexView, self).get_context_data(**kwargs)
		context['form'] = CaseForm()
		return context


class CaseView(DetailView):
	'''
  The genertic class for case view, a detailed overview of a case. 
  This view also renders err message based on the error code in the GET
  query string, if redirected from '/start_alloc'. See below for detailed 
  explanation of error code
	'''
	template_name = 'room/case_detail.html'
	model = Case

	err_msg = {
		1: "The identity you selected is invalid. Please try again.",
		2: "The idendity you selected has already logged in. Please try again.",
	}

	def get_context_data(self, **kwargs):
		context = super(CaseView, self).get_context_data(**kwargs)
		groups = Group.objects.filter(case=self.object).order_by("name")
		context['groups'] = groups
		rooms = Room.objects.filter(case=self.object).order_by("name")
		context['rooms'] = rooms
		context['case_form'] = ReadOnlyCaseForm(instance=self.object)
		context['renters'] = Group.objects.filter(case=self.object)
		context['room_form'] = RoomForm(initial={'case':self.object})
		context['group_form'] = GroupForm(initial={'case':self.object})
		context['session_form'] = SessionForm(self.object)
		# If case is completed, show scheme and don't show login
		alloc = Allocation.objects.get(case=self.object)
		# print(alloc.is_complete)
		if alloc.is_complete():
			proposal_raw = alloc.get_archived_division()
			proposal = []
			for i, division in enumerate(proposal_raw):
				proposal.append({
					'group': groups[i],
					'room': rooms[division['room']],
					'rent': division['rent'],
				})
			context['proposal'] = proposal

		# If case is not able to begin, disable the button
		group_num = Group.objects.filter(case=self.object).count()
		room_num = Room.objects.filter(case=self.object).count()
		context['can_begin'] = group_num != 0 and group_num == room_num

		# If there is err_msg in GET query, include it in context
		if self.request.GET.get("err"):
			err_code = int(self.request.GET.get("err"))
			context['err_msg'] = CaseView.err_msg[err_code]
		return context


#### Out dataed. Allocation page will be a dialog inside /case/<case_name>/ #### 
# class AllocView(DetailView):
# 	template_name = 'room/alloc_detail.html'
# 	model = Allocation

# 	def get_context_data(self, **kwargs):
# 		context = super(AllocView, self).get_context_data(**kwargs)
# 		context['groups'] = Group.objects.filter(case=self.object.case)
# 		context['rooms'] = Room.objects.filter(case=self.object.case)
# 		context['case_form'] = ReadOnlyCaseForm(instance=self.object.case)
# 		return context


#### Out dataed. Use channel instead ##### 
# def start_alloc(request, pk):
# 	if request.method == 'POST':
# 		case = get_object_or_404(Case, pk=pk)
# 		form = SessionForm(case, request.POST)
# 		if form.is_valid():
# 			# Log in the group
# 			group_name = form.cleaned_data['group']
# 			group = get_object_or_404(Group, case=case, name=group_name)
# 			group.login(request.user)
# 			alloc = get_object_or_404(Allocation, pk=case)
# 			if alloc.is_ready():
# 				# Setup is_ready message
# 				messages.add_message(request, messages.INFO, "ready", group.case)
# 			return redirect("room:alloc", pk=group.case.name)
# 		else:
# 			return redirect(request.META.get('HTTP_REFERER') + "?err=1")
# 	else:
# 		return HttpResponseNotFound('<h3>Page not found</h3>')


# Method for creating a case
def create_case(request):
	if request.method == 'POST':
		form = CaseForm(request.POST, request.FILES)
		if form.is_valid():
			form.save()
			# Create an associated alloction object
			alloc = Allocation(form.cleaned_data['name'])
			alloc.save()
			return redirect('room:index')
		else:
			return render(request, 'room/index.html', {'form':form})

	else:
		return HttpResponseNotFound('<h3>Page not found</h3>')

def about(request):
	return render(request, 'room/about.html')


# Method for creating a room
def create_room(request):
	if request.method == 'POST':
		form = RoomForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect(request.META.get('HTTP_REFERER'))
		else:
			return redirect(request.META.get('HTTP_REFERER'))

	else:
		return HttpResponseNotFound('<h3>Page not found</h3>')

# Method for creating a group
def create_group(request):
	if request.method == 'POST':
		form = GroupForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect(request.META.get('HTTP_REFERER'))
		else:
			return redirect(request.META.get('HTTP_REFERER'))

	else:
		return HttpResponseNotFound('<h3>Page not found</h3>')

room/templates/room/about.html
{% extends 'room/base.html' %}
{% load staticfiles%}

{% block title %}
Room Allocation - About
{% endblock %}

{% block head %}
{{ block.super }}
{% endblock %}

{% block body %}
{{ block.super }}
<xmp theme="united" style="display:none;">
## Room-Allocation: Spernel's labeling algorithm for fair rent division 
---------------
### What is it?
Room-Allocation is a web application that helps you solve the fair rent division problem. Since people's preference for goods are related to their prices, it is often hard to come up with a fair rent division such that every participant is satisfied with the price as well as the room. We are here to help you generate a fair division scheme, and giving everyone that shares the rent an equal opportunity to participate.

---------------
### How does it work?
- This is a proof-of-concept web application inspired by [Dr. Francis Su's paper](https://www.math.hmc.edu/~su/papers.dir/rent.pdf). Essentially, it applies Spernel's labeling to generate an envy-free rent division.

- During each turn, the algorithm comes up with a pricing scheme which contains a price for each room, and asks a user to choose the room he prefers. The algorithm then chooses another user to ask with a slightly different pricing scheme, repeating itself until every user chooses a different room for the same pricing scheme, within a reasonable accuracy.

- When the algorithm terminates, it asks every participant whether they will go for the division scheme. If every one agrees, it archives the solution, and the solution can be seen every time a user access the case page. If one of the participant chooses to go on for a more accurate scheme, the procedure will continue.

- It can be mathematically proven that it is possible to come up with a scheme such that every participant will choose a different room. Essentially, it is a n-dimensional spernel labeling problem.

----------------
### Source code
- This project is a web app based on Django. If you would like to see the source code, please visit its project repo on [github](https://github.com/dianchen96/Room-Allocation).

</xmp>
<script src="http://strapdownjs.com/v/0.2/strapdown.js"></script>
{% endblock %}

room/templates/room/base.html
{% load staticfiles %}
{% block head %}
<link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
<link rel="stylesheet" href="{% static 'room/style.css' %}">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
{% endblock head %}

{% block body %}
<div class="pure-menu pure-menu-horizontal custom-menu-bar">
    <ul class="pure-menu-list custom-menu-list">
        <li class="pure-menu-item custom-menu-item"><a href="{% url 'room:index' %}" class="pure-menu-link">Home</a></li>
        <li class="pure-menu-item custom-menu-item"><a href="{% url 'room:about' %}" class="pure-menu-link">About</a></li>
    </ul>
</div>
</br>
{% endblock body %}

room/templates/room/case_detail.html
{% extends 'room/base.html' %}
{% load staticfiles%}

{% block title %}
Room Allocation - {{ object.name }}
{% endblock %}

{% block head %}
{{ block.super }}
<script src="{% static 'room/allocation.js' %}"></script>
<script src="{% static 'room/spin.min.js' %}"></script>
{% endblock %}

{% block body %}
{{ block.super }}
<div class="content-wrap">
	<p hidden id="case_name">{{ object.name }}</p>
	<h3>Room Allocation - {{ object.name }}</h3>
	<hr>
	<button class="pure-button custom-toggle" data-toggle="collapse" data-target="#case-info">Case Information</button>
	<div id="case-info" class="collapse">
		<table class="pure-table pure-table-horizontal custom-table">
			{{ case_form.as_table }}
		</table>
	</div>
	<button class="pure-button custom-toggle" data-toggle="collapse" data-target="#room-config">Room Configuration</button>
	<div id="room-config" class="collapse">
		<hr>
		<img src="{{ case_form.instance.img.url }}" />
	</div>
	<button class="pure-button custom-toggle" data-toggle="collapse" data-target="#room-info">Room Information</button>
	<div id="room-info" class="collapse">
		<table class="pure-table pure-table-striped custom-table">
			<thead>
				<tr><th>Room Name</th></tr>
			</thread>	
			<tbody>
				{% for room in rooms %}
					<tr><th class="room-name">{{ room }}</th></tr>
				{% endfor %}
			</tbody>
		</table>
	<h3 class="custom-create-title">Create New Room</h3>
		<form class="pure-form" action="/room/create-room/", method="POST" data-ajax="false">
			{% csrf_token %}
    	<fieldset>
			<table class="pure-table pure-table-horizontal custom-table">
				{{ room_form.as_table }}
			</table>
			<button type="submit" class="pure-button pure-button-primary">Create</button>
			</fieldset>
		</form>
	</div>
	<button class="pure-button custom-toggle" data-toggle="collapse" data-target="#group-info">Group Configuration</button>
	<div id="group-info" class="collapse"> 
	<table class="pure-table pure-table-striped custom-table">
			<thead>
				<tr><th>Group Name</th><th>Number of Person</th></tr>
			</thread>	
			<tbody>
				{% for renter in renters %}
					<tr><th class="group-name">{{ renter.name }}</th><th>{{ renter.num_of_renters }}</th></tr>
				{% endfor %}
			</tbody>
	</table>
	<h3 class="custom-create-title">Create New Group</h3>
		<form class="pure-form" action="/room/create-group/", method="POST" data-ajax="false">
			{% csrf_token %}
    	<fieldset>
			<table class="pure-table pure-table-horizontal custom-table">
				{{ group_form.as_table }}
			</table>
			<button type="submit" class="pure-button pure-button-primary">Create</button>
			</fieldset>
		</form>
	</div>
	{% if proposal %}
		<button class="pure-button custom-toggle" data-toggle="collapse" data-target="#division-info">Division Scheme</button>
		<div id="division-info" class="collapse in">
			<table class="pure-table pure-table-horizontal custom-table">
				<thead>
					<tr>
						<th>Group</th><th>Room</th><th>Rent</th>
					</tr>
				</thead>
				<tbody>
					{% for division in proposal %}
						<tr>
							<th>{{ division.group }}</th>
							<th>{{ division.room }}</th>
							<th>{{ division.rent }}</th>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	{% endif %}

	<h3>Choose Your Identity</h3>
	<!--If user has selected an invalid identity and redirected back -->
	<p class="err-msg">{{ err_msg }}</p>
	<form id="identity_form" class="pure-form pure-form-aligned">
		{% csrf_token %}
		<fieldset>
			{{ session_form }}
			{% if can_begin %}
				<button id="confirm_identity" class="pure-button pure-button-primary">Start Allocation</button> 
			{% else %}
				<button id="confirm_identity" class="pure-button pure-button-disabled" disabled>Start Allocation</button>
			{% endif %}
	</fieldset>
	</form>
	<!-- Waiting modal -->
	<div class="modal fade" id="waiting_modal" role="dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h4>Waiting for other groups</h4>
			</div>
			<div id="spinner" class="modal-body">
				<!-- Waiting animation -->
			</div>
			<div class="modal-footer">
				<button id="cancel_alloc" class="pure-button">Cancel</button>
			</div>
		</div>
	</div>	
	<!-- Allocation modal -->
	<div class="modal fade" id="alloc_modal" role="dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h4>Which room will you choose?</h4>
			</div>
			<div id="price_scheme" class="modal-body pure-grid-g">
				<!-- pricing scheme, setup by allocation.js -->
			</div>
		</div>
	</div>	
	<!-- Division modal -->
	<div class="modal fade" id="division_modal" role="dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h4>Here is a fair division scheme. Will you go for it?</h4>
			</div>
			<div id="division_scheme" class="modal-body pure-grid-g">
				<!-- pricing scheme, setup by allocation.js -->
			</div>
		</div>
	</div>	
</div>

{% endblock %}

room/templates/room/index.html
{% extends "room/base.html" %}

{% block title %}
Room Allocation
{% endblock %}

{% block head %}
{{ block.super }}
{% endblock %}

{% block body %}
{{ block.super }}
<div class="content-wrap">
	<h3>All Cases</h3>
	<table class="pure-table pure-table-striped custom-table">
		<thead>
			<tr>
				<th>Name</th>
        <th>Created Time</th>
			</tr>
		</thead>
		<tbody>
			{% for case in object_list %}
				<tr><th><a href="{% url 'room:case' case.name %}">{{ case.name }}</th><th>{{ case.created_date }}</th></tr> 
			{% endfor %}
		</tbody>
	</table>

	<h3>Create a New Case</h3>
	<form enctype="multipart/form-data" class="pure-form pure-form-stacked custom-form" action="/room/create-case/", method="POST" data-ajax="false">
		{% csrf_token %}
    <fieldset>
        <div class="pure-g">
            <div class="pure-u-1 pure-u-md-1-3">
            		{{ form.name.errors }}
                <label for="{{ form.name.id_for_label }}">Name</label>
                {{ form.name }}
            </div>
            <div class="pure-u-1 pure-u-md-1-3">
            		{{ form.rent.errors }}
            		<label for="{{ form.rent.id_for_label }}">Rent Amount</label>
            		{{ form.rent }}
            </div>
            <div class="pure-u-1 pure-u-md-1-3">
            		{{ form.img.errors }}
                <label for="{{ form.img.id_for_label }}">Image</label>
								{{ form.img }}
            </div>
            <div class="pure-u-1 pure-u-md-1-3">
            		{{ form.created_date.errors }}
								{{ form.created_date.as_hidden }}
            </div>

        </div>
        <button type="submit" class="pure-button pure-button-primary">Create</button>
    </fieldset>
	</form>
</div>
{% endblock %}